### PR TITLE
fix: move unneeded ts types to devDeps

### LINKED ISSUE #127: move @types/* packages to devDependencies
If they are in dependencies, it enforces packages that depends on chrome-launcher to install the packages with same versions (@types/core-js, @types/rimraf, @types/mkdirp, @types/node and their dependencies).

So please add them as devDependencies.

### PR DESCRIPTION
**Pull request by patrickhulce**
closes #127

### CODE REVIEW

File: src/chrome-launcher.ts [hunk 1]
```diff
@@ -50,7 +52,7 @@ export interface LaunchedChrome {
 
 export interface ModuleOverrides {
   fs?: typeof fs;
-  rimraf?: typeof rimraf;
+  rimraf?: RimrafModule;
```
Comment (brendankenny) [inline src/chrome-launcher.ts]: why'd we need this?

File: package.json [hunk 2]
```diff
@@ -21,10 +23,7 @@
     "typescript": "2.7.1"
   },
   "dependencies": {
-    "@types/core-js": "^0.9.41",
-    "@types/mkdirp": "^0.3.29",
-    "@types/node": "^9.3.0",
-    "@types/rimraf": "^0.0.28",
+    "@types/node": "*",
```
Comment (brendankenny) [inline package.json]: 🎉 🎉

File: src/chrome-launcher.ts (hunk 1 above)
Comment (patrickhulce) [reply src/chrome-launcher.ts]: well if we want our users to not need `@types/rimraf` then we can't do `import 'rimraf'` in our `d.ts` files.

because we export this type here, we need to replace this. it's just one function so it seems pretty easy to type ourselves

Comment (brendankenny) [reply src/chrome-launcher.ts]: oh, lol, just noticed the interface. Oh `chrome-launcher`...
